//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int id { get; set; }
        public string name { get; set; }
        public double average_price { get; set; }
        public string brand_name { get; set; }
    }
}
